apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-argocd-apps-reload
subjects:
  - kind: ServiceAccount
    name: k8s-argocd-apps-reload
roleRef:
  kind: ClusterRole
  name: k8s-argocd-apps-reload
  apiGroup: rbac.authorization.k8s.io
