apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-argocd-apps-reload-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: k8s-argocd-apps-reload
    app.kubernetes.io/instance: k8s-argocd-apps-reload
    app.kubernetes.io/managed-by: Kustomize
data:
  dc_number: dc007
  env_name: stage
  service_to_reload: nginx-deployment
