apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - reloadjob.yaml
images:
- name: k8s-argocd-apps-reload
  newName: bitnami/kubectl
  newTag: latest  
