apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-argocd-apps-reload
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
#  namespace: nstest1
spec:
  ttlSecondsAfterFinished: 300
  #successfulJobsHistoryLimit: 1
  #failedJobsHistoryLimit: 2
  #concurrencyPolicy: Forbid
  template:
    spec:
      #parallelism: 1
      #completions: 1
      #backoffLimit: 2 
      activeDeadlineSeconds: 300
      serviceAccountName: k8s-argocd-apps-reload
      restartPolicy: Never
      volumes:
      - name: k8s-argocd-apps-reload
        configMap:
          name: k8s-argocd-apps-reload
      containers:
      - name: kubectl
        image: bitnami/kubectl 
        env:
            - name: SERVICE_NAMES
              valueFrom:
                configMapKeyRef:
                  name: k8s-argocd-apps-reload
                  key: service_to_reload
        #command: ["echo"]
        #args: ["$(SERVICE_NAMES)"]  
        volumeMounts:
          - mountPath: /work
            name: k8s-argocd-apps-reload
        command:
            - 'ls'
            - '/work'
            # - 'kubectl'
            # - 'rollout'
            # - 'restart'
            # - 'deployment/test'
