apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: nginx-deployment
bases:
  - ../../base
commonLabels:
  env: test
images:
- name: nginx-image
  newName: nginx
  newTag: latest
