apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: nginx-deployment
bases:
  - ../../base
commonLabels:
  env: test
patches:
- target:
    kind: CronJob
    name: deployment-restart-job
  patch: |-
    - op: replace
      path: /spec/schedule
      value: '*/2 * * * *' 
    # - op: replace
    #   path: /spec/jobTemplate/spec/template/spec/containers/command
    #   value: 
    #      - 'kubectl'
    #      - 'rollout'
    #      - 'restart'
    #      - 'deployment/nginx-deployment'
images:
- name: nginx-image
  newName: nginx
  newTag: latest
