apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-argocd-apps-reload
data:
  service_to_reload: |
    - nginx-deployment
    - k8s-web-app2
    - k8s-web-app3
    - k8s-web-app4
    - k8s-web-app5
    - k8s-web-app6
    - k8s-web-app7
    - k8s-web-app8
    - k8s-web-app9
