apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-argocd-apps-reload
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
              command:
                - ['echo', '$SERVICE_NAMES']
