apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-argocd-apps-reload
resources:
  - ../../../base_job1
commonLabels:
  env: test
patchesStrategicMerge:
  - configmap12.yaml
# configMapGenerator:
#   - name: k8s-argocd-apps-reload-config
#     behavior: merge  
images:
- name: k8s-argocd-apps-reload
  newName: priyadarshee2019/python_kubectl
  newTag: v3.0
