apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: restart-job
commonLabels:
  env: test
resources:
- role_binding.yaml 
- roles.yaml
- service_account.yaml
- restart_cronJob.yaml
- kustomization.yaml
images:
- name: kubectl
  newName: bitnami/kubectl
  newTag: latest
