apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart-job
  namespace: restart-job
spec:
  concurrencyPolicy: Forbid
  schedule: '*/10 0 * * *'
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: deployment-restart-sa 
          restartPolicy: Never
          containers:
            - name: kubectl
              image: kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/${DEPLOYMENT}'
