apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-deployment
bases:
  - ../../base
commonLabels:
  env: test
patches:
- target:
    kind: Ingress
    name: nginx-deployment
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: nginx-env1.k8s.local
- target:
    kind: HorizontalPodAutoscaler
    name: nginx-deployment
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 4
images:
- name: nginx-image
  newName: nginx
  newTag: latest
