apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart-job-role
  namespace: restart-job
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]
