apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-restart-rb
  namespace: restart-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart-sa 
    namespace: ["nginx-deployment1", "nginx-deployment1"]
