apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: "mysql"
