# Custom error page configMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom_error_pages
  namespace: ingress-nginx
data:
  404: |
    <!DOCTYPE html>
    <html>
      <head><title>PAGE NOT FOUND from custom</title></head>
      <body>PAGE NOT FOUND from custom</body>
    </html>
  503: |
    <!DOCTYPE html>
    <html>
      <head><title>CUSTOM SERVICE UNAVAILABLE</title></head>
      <body>CUSTOM SERVICE UNAVAILABLE</body>
    </html>
