apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_federation, rabbitmq_peer_discovery_k8s, rabbitmq_management].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    log.file.level = debug
    log.console = true
    log.console.level = debug
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    queue_master_locator=min-masters
    loopback_users.guest = false
    listeners.tcp.default = 5672
    cluster_formation.randomized_startup_delay_range.min = 0
    cluster_formation.randomized_startup_delay_range.max = 2
    cluster_formation.k8s.service_name = rabbitmq-cluster
    cluster_formation.k8s.hostname_suffix = .rabbitmq-cluster.testns-rabbitmq.svc.cluster.local
    # ssl_options.verify = verify_peer
    # listeners.ssl.default = 5671
    # ssl_options.fail_if_no_peer_cert = true
    # ssl_options.cacertfile = /etc/rabbitmq/certs/ca_certificate.pem
    # ssl_options.certfile = /etc/rabbitmq/certs/server_certificate.pem
    # ssl_options.keyfile = /etc/rabbitmq/certs/server_key.pem
