apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: testns-rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_federation, rabbitmq_peer_discovery_k8s, rabbitmq_management].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.port = 443
    cluster_formation.k8s.token_path = /var/run/secrets/kubernetes.io/serviceaccount/token
    cluster_formation.k8s.cert_path = /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    cluster_formation.k8s.namespace_path = /var/run/secrets/kubernetes.io/serviceaccount/namespace
    log.file.level = debug
    log.console = true
    log.console.level = debug
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    queue_master_locator=min-masters
    loopback_users.guest = false
    listeners.tcp.default = 5672