apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
  namespace: testns-rabbitmq
spec:
  rules:
  - host: rabbitcls2.local.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rabbitmq-console
              port:
                number: 15672
